URL<-"http://fuzzylife.org/"
download.file(URL,paste0("data.html"), mode = 'wb')
getwd()
rawHTML <- paste(readLines("data.html"))#, collapse="\n")
write.csv(as.data.frame(rawHTML),paste0("data_html.csv"))
cn<-rawHTML[grep("<title>",rawHTML)]
cn<-gsub("</title>","",cn)
cn<-gsub("<title>Bg. ","",cn)
cn<-gsub(" ","",fixed=T,cn)
print(cn)
shloka<-rawHTML[grep("r r-lang-en r-translation",rawHTML)]
shlokaClean<-gsub(".*r r-lang-en r-translation(.+)div.*", "\\1", shloka)
shlokaClean<-gsub(" ><p><strong>", "\n", shlokaClean)
shlokaClean<-gsub(" ><p><strong>", "\n", shlokaClean)
shlokaClean<-gsub("</strong></p></", "\"\n", shlokaClean)
shlokaClean<-gsub("\\s*\\[[^\\)]+\\]","",shlokaClean)
shlokaClean<-gsub("â€“","-",shlokaClean)
#https://rstudio-pubs-static.s3.amazonaws.com/279354_f552c4c41852439f910ad620763960b6.html
#Encoding(shlokaClean)
#Encoding('ʘ')
#print(Sys.info()[1:6])
#getOption("encoding")
#Sys.getlocale("LC_ALL")
#length(unique(iconvlist()))
#results <-  sapply(iconvlist(),         function(to)           try(iconv(x, from = Encoding(x), to = to), silent = TRUE))
#sum(isErrors <- grepl("^Error in", results))
#errors <- results[isErrors]
#names(errors)
#shlokaClean<-iconv(shlokaClean, "latin1", "ASCII//TRANSLIT")
shlokaClean<-paste(strwrap(shlokaClean,width=50),collapse="\n")
writeLines(shlokaClean,paste0("data_html.txt"))
URL<-paste0("Chapter.Verse-",cn)
png("data.png")
par(mar = c(0,0,0,0),bg = "chocolate",family = 'mono')
plot(c(0, 1), c(0, 1), ann = F, bty = 'n', type = 'n', xaxt = 'n', yaxt = 'n')
text(x = 0.5, y = 0.75, paste(URL,"\n",shlokaClean),cex = 1.2, col = "white")
dev.off()
