name: Gita
on:
  schedule:
    - cron: "30 5 * * *"
permissions:
  contents: write
jobs:
  build:
    runs-on:  ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: |
            sudo apt -y update
            sudo apt install -y r-base
            Rscript R/gita.r 
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git add --all
            git commit -am "add data"
            git push
